package com.fasolutions.finance.application.model

data class CompanyReport(
    val code: String,
    val sector: String,
    val subSector: String,
    val type: String,
    val name: String,
    val dividendLastFiveYears: Double,
    val dividendLastTwoYears: Double,
    val fairPricePercent: Double,
    val price: Double,
    val fairPrice: Double,
    val lpa: Double,
    val vpa: Double,
    val lpaPricePercent: Double,
    val quantity: Int?,
    val averagePrice: Double?,
    val averagePricePercent: Double?,
    val totalPrice: Double?,
    val roic: Double,
    val totalPercent: Double,
    val fairAveragePrice: Double,
    val fairAveragePricePercent: Double,
    val valorization30Days: Double,
    val valorization5Days: Double,
    val observedPayout: Double,
    val dividendNextTreeYears: Double,
    val filtered: Boolean
)
